//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoPromocao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMIDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSUMIDOR()
        {
            this.TB_USUARIO_SISTEMA = new HashSet<USUARIO_SISTEMA>();
        }
    
        public int ID_CONSUMIDOR { get; set; }
        public int RG_C { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string EMAIL { get; set; }
        public string SEXO { get; set; }
        public string FRASE_DE_SEGURANCA { get; set; }
        public string SENHA { get; set; }
        public System.DateTime DATA_DE_NASCIMENTO { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string CIDADE { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_SISTEMA> TB_USUARIO_SISTEMA { get; set; }
    }
}
