//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoPromocao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.TB_USUARIO_EMPRESA = new HashSet<USUARIO_EMPRESA>();
        }
    
        public int ID_EMPRESA { get; set; }
        public int CNPJ { get; set; }
        public string BAIRRO { get; set; }
        public string SENHA { get; set; }
        public string FRASE_SEGURANCA { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string SOLICITANTE { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string NOME { get; set; }
        public string RUA { get; set; }
        public Nullable<int> NUMERO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_EMPRESA> TB_USUARIO_EMPRESA { get; set; }
    }
}
