//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoPromocao.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROJETO_SAD_ESIIEntities : DbContext
    {
        public PROJETO_SAD_ESIIEntities()
            : base("name=PROJETO_SAD_ESIIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> TB_ADMINISTRADOR { get; set; }
        public virtual DbSet<CONSUMIDOR> TB_CONSUMIDOR { get; set; }
        public virtual DbSet<EMPRESA> TB_EMPRESA { get; set; }
        public virtual DbSet<PROMOCAO> TB_PROMOCAO { get; set; }
        public virtual DbSet<USUARIO_EMPRESA> TB_USUARIO_EMPRESA { get; set; }
        public virtual DbSet<USUARIO_SISTEMA> TB_USUARIO_SISTEMA { get; set; }
    }
}
